<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tribefire.extension.web-api</groupId>
        <artifactId>parent</artifactId>
        <version>[1.0,1.1)</version>
    </parent>
    <artifactId>http-client-test</artifactId>
    <version>1.0.1</version>
    <properties><archetype>test</archetype></properties>
    <dependencies>
        <dependency>
            <groupId>com.braintribe.gm</groupId>
            <artifactId>gm-unit-test-deps</artifactId>
            <version>${V.com.braintribe.gm}</version>
        </dependency>
        <dependency>
            <groupId>tribefire.extension.web-api</groupId>
            <artifactId>http-client</artifactId>
            <version>${V.tribefire.extension.web-api}</version>
        </dependency>
        <dependency>
            <groupId>tribefire.extension.web-api</groupId>
            <artifactId>web-api-client-meta-data-annotations</artifactId>
            <version>${V.tribefire.extension.web-api}</version>
        </dependency>
        <dependency>
            <groupId>tribefire.extension.web-api</groupId>
            <artifactId>web-api-client</artifactId>
            <version>${V.tribefire.extension.web-api}</version>
        </dependency>
        <dependency>
            <groupId>tribefire.extension.web-api</groupId>
            <artifactId>web-api-client-module</artifactId>
            <version>${V.tribefire.extension.web-api}</version>
        </dependency>
    </dependencies>
</project>
